# Global LLM configuration
[llm]
model = "Qwen/Qwen2.5-7B-Instruct"
base_url = "https://api.siliconflow.cn/v1"
api_key = "sk-enxnmkeywnjpwsurmphgviocinitanctlsirpyucgvirxnfk"
max_tokens = 4096
temperature = 0.0

# Optional configuration for specific LLM models
[llm.vision]
model = "Qwen/Qwen2.5-7B-Instruct"
base_url = "https://api.siliconflow.cn/v1"
api_key = "sk-enxnmkeywnjpwsurmphgviocinitanctlsirpyucgvirxnfk"
